spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=${PASSWORD}
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ????????? ???? (?????? ???? ??????? ? ? ????????? Base64)
jwt.secret=984hg493gh0439hg0439hg0439hg0439hg0439hg0439hgfdsfdsfdsfdfdsfsd
# ????? ????? ?????? ? ?????????????
jwt.lifetime=3600000